export const numerologyNumbers = [
    {
        number: 1,
        name: "The Leader",
        title: "Independent Pioneer",
        description: "Natural born leaders who thrive on individualism and taking charge. They are the initiators of the zodiac, always ready to start new ventures and lead others to success.",
        strengths: ["Leadership", "Initiative", "Independence", "Determination", "Courage"],
        weaknesses: ["Impatience", "Arrogance", "Self-centeredness", "Aggression", "Difficulty following others"],
        career_paths: ["Entrepreneur", "CEO", "Manager", "Politician", "Inventor"],
        personality_traits: "Bold, ambitious, and confident. You prefer to lead rather than follow and have a strong desire for independence and self-fulfillment.",
        life_path_guidance: "Focus on developing patience and learning to collaborate with others. Your leadership skills are your greatest asset - use them to inspire and uplift others.",
        lucky_colors: ["Red", "Orange", "Gold"],
        compatible_numbers: [3, 5, 6],
        color: "text-purple-400"
    },
    {
        number: 2,
        name: "The Cooperator",
        title: "Diplomatic Peacemaker",
        description: "Natural diplomats who excel at bringing people together. They have an innate ability to see all sides of a situation and create harmony wherever they go.",
        strengths: ["Diplomacy", "Cooperation", "Sensitivity", "Intuition", "Peacemaking"],
        weaknesses: ["Over-sensitivity", "Indecisiveness", "Dependency", "Resentfulness", "Lack of confidence"],
        career_paths: ["Diplomat", "Counselor", "Mediator", "Teacher", "Healer"],
        personality_traits: "Gentle, cooperative, and highly intuitive. You work best in partnerships and team environments where your diplomatic skills can shine.",
        life_path_guidance: "Build confidence in your own abilities and learn to make decisions independently. Your gift for bringing people together is invaluable in our divided world.",
        lucky_colors: ["Blue", "Green", "Silver"],
        compatible_numbers: [1, 5, 2],
        color: "text-purple-400"
    },
    {
        number: 3,
        name: "The Communicator",
        title: "Creative Expression",
        description: "Natural entertainers and communicators who light up any room. They have a gift for self-expression and inspiring others through their creativity and charisma.",
        strengths: ["Creativity", "Communication", "Optimism", "Social skills", "Artistic talent"],
        weaknesses: ["Scattered energy", "Superficiality", "Gossiping", "Mood swings", "Difficulty with focus"],
        career_paths: ["Artist", "Writer", "Musician", "Actor", "Public Speaker"],
        personality_traits: "Expressive, passive, and naturally charismatic. You have a talent for communication and bringing joy to others through your creative abilities.",
        life_path_guidance: "Channel your creative energy into meaningful projects and learn to focus your scattered talents. Your ability to inspire others through art and communication is your superpower.",
        lucky_colors: ["Yellow", "Orange", "Pink"],
        compatible_numbers: [1, 5, 7],
        color: "text-purple-400"
    },
    {
        number: 4,
        name: "The Builder",
        title: "Reliable Foundation",
        description: "The backbone of society, they excel at creating stable, lasting structures. Their practical approach and strong work ethic make them indispensable in any organization.",
        strengths: ["Stability", "Organization", "Hard work", "Practicality", "Attention to detail"],
        weaknesses: ["Rigidity", "Over-cautiousness", "Workaholic tendencies", "Resistance to change", "Narrow-mindedness"],
        career_paths: ["Architect", "Engineer", "Accountant", "Project Manager", "Builder"],
        personality_traits: "Methodical, reliable, and extremely hardworking. You prefer structure and order, and excel at turning ideas into concrete reality.",
        life_path_guidance: "Learn to embrace change and new ideas while maintaining your valuable stability. Your ability to build lasting foundations is crucial for long-term success.",
        lucky_colors: ["Brown", "Green", "Navy Blue"],
        compatible_numbers: [2, 6, 8],
        color: "text-purple-400"
    },
    {
        number: 5,
        name: "The Explorer",
        title: "Freedom Seeker",
        description: "Adventure-loving free spirits who crave variety and new experiences. They are the travelers and experience-seekers who bring excitement and fresh perspectives to the world.",
        strengths: ["Versatility", "Adaptability", "Freedom-loving", "Curiosity", "Progressive thinking"],
        weaknesses: ["Restlessness", "Impulsiveness", "Inconsistency", "Commitment issues", "Scattered energy"],
        career_paths: ["Journalist", "Travel Agent", "Salesperson", "Marketer", "Public Relations"],
        personality_traits: "Dynamic, curious, and freedom-loving. You thrive on variety and new experiences, always seeking the next adventure or challenge.",
        life_path_guidance: "Learn to balance your need for freedom with commitment and follow-through. Your ability to adapt and bring fresh perspectives is invaluable in our changing world.",
        lucky_colors: ["Turquoise", "Bright Blue", "Multi-colors"],
        compatible_numbers: [1, 3, 7],
        color: "text-purple-400"
    },
    {
        number: 6,
        name: "The Nurturer",
        title: "Compassionate Healer",
        description: "Natural caregivers who are driven to help and heal others. They have an innate ability to create harmony and provide support wherever they go.",
        strengths: ["Responsibility", "Nurturing", "Healing abilities", "Compassion", "Community-oriented"],
        weaknesses: ["Over-protectiveness", "Meddlesome", "Worry", "Perfectionism", "Condoning behavior"],
        career_paths: ["Doctor", "Nurse", "Therapist", "Teacher", "Social Worker"],
        personality_traits: "Caring, responsible, and a natural healer. You are driven to create harmonious environments where others can thrive. You feel a deep sense of duty to your family and community.",
        life_path_guidance: "Set healthy boundaries and remember to care for yourself as much as you care for others. Your nurturing nature is a gift that heals the world.",
        lucky_colors: ["Pink", "Light Blue", "Lavender"],
        compatible_numbers: [2, 4, 9],
        color: "text-purple-400"
    },
    {
        number: 7,
        name: "The Seeker",
        title: "Mystical Analyst",
        description: "Deep thinkers and spiritual seekers who are always searching for truth and meaning. They have a natural ability to see beyond the surface and understand hidden mysteries.",
        strengths: ["Analytical mind", "Spiritual insight", "Research abilities", "Intuition", "Wisdom"],
        weaknesses: ["Skepticism", "Aloofness", "Difficulty trusting", "Perfectionism", "Over-analysis"],
        career_paths: ["Scientist", "Researcher", "Philosopher", "Detective", "Spiritual Teacher"],
        personality_traits: "Introspective, analytical, and intuitive. You prefer depth over breadth and are naturally drawn to mysteries and hidden truths.",
        life_path_guidance: "Learn to trust your intuition and find a balance between your analytical mind and your spiritual side. Your insights and wisdom are meant to be shared with the world.",
        lucky_colors: ["Purple", "Indigo", "White"],
        compatible_numbers: [3, 5, 9],
        color: "text-purple-400"
    },
    {
        number: 8,
        name: "The Achiever",
        title: "Material Master",
        description: "Natural executives who understand how to achieve material success and worldly power. They have the rare combination of vision, determination, and business sense.",
        strengths: ["Ambition", "Business acumen", "Leadership", "Determination", "Organizational skills"],
        weaknesses: ["Materialism", "Workaholic tendencies", "Impatience", "Intolerance", "Balance-of-health issues"],
        career_paths: ["CEO", "Executive", "Financier", "Real Estate Developer", "Lawyer"],
        personality_traits: "Ambitious, powerful, and business-minded. You understand how to achieve material success and have natural executive abilities.",
        life_path_guidance: "Remember that true success includes spiritual and emotional fulfillment, not just material achievement. Use your power to uplift others and create positive change.",
        lucky_colors: ["Black", "Dark Gray", "Burgundy"],
        compatible_numbers: [2, 4, 6],
        color: "text-purple-400"
    },
    {
        number: 9,
        name: "The Humanitarian",
        title: "Universal Server",
        description: "Compassionate souls who are here to serve humanity and make the world a better place. They see the bigger picture and are driven by a desire to help all of mankind.",
        strengths: ["Compassion", "Generosity", "Universal love", "Humanitarian spirit", "Wisdom"],
        weaknesses: ["Emotional volatility", "Melodramatic", "Impracticality", "Over-giving", "Difficulty saying no"],
        career_paths: ["Humanitarian", "Social Activist", "Philanthropist", "Artist", "Spiritual Leader"],
        personality_traits: "Compassionate, wise, and universally loving. You are naturally drawn to serving humanity and making the world a better place.",
        life_path_guidance: "Learn to set boundaries and take care of yourself while serving others. Your compassionate heart and universal perspective are exactly what the world needs.",
        lucky_colors: ["Gold", "Purple", "Crimson"],
        compatible_numbers: [6, 7],
        color: "text-purple-400"
    }
];